In [92]:
%load_ext autoreload
%autoreload 2

from shrimpgrad.tensor import Tensor
import torch

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [63]:
t1 = torch.arange(10).reshape(2,5)
t2 = torch.arange(10).reshape(5,2)
t1.matmul(t2)

tensor([[ 60,  70],
        [160, 195]])

In [64]:
t1 = Tensor.arange(10).reshape(2,5)
t2 = Tensor.arange(10).reshape(5,2)
t1.matmul(t2)


tensor([[60.0, 70.0], [160.0, 195.0]])

In [68]:
t1 = torch.arange(10, dtype=torch.float32).reshape(5,2)
t2 = torch.arange(10, dtype=torch.float32).reshape(2,5)
t1.matmul(t2)

tensor([[  5.,   6.,   7.,   8.,   9.],
        [ 15.,  20.,  25.,  30.,  35.],
        [ 25.,  34.,  43.,  52.,  61.],
        [ 35.,  48.,  61.,  74.,  87.],
        [ 45.,  62.,  79.,  96., 113.]])

In [66]:
# Add @ for matmul
t1 = Tensor.arange(10).reshape(2,5)
t2 = Tensor.arange(10).reshape(5,2)

t1 @ t2


tensor([[60.0, 70.0], [160.0, 195.0]])

In [67]:
t2 @ t1

tensor([[5.0, 6.0, 7.0, 8.0, 9.0],
 [15.0, 20.0, 25.0, 30.0, 35.0],
 [25.0, 34.0, 43.0, 52.0, 61.0],
 [35.0, 48.0, 61.0, 74.0, 87.0],
 [45.0, 62.0, 79.0, 96.0, 113.0]])

In [69]:
# Dtype
t1.dtype

torch.float32

In [70]:
t1 = Tensor.arange(6, dtype=shrimp.dtypes.int32)
t1

tensor([0, 1, 2, 3, 4, 5])

In [71]:
t2 = Tensor.arange(6, dtype=shrimp.dtypes.float32)
t2

tensor([0.0, 1.0, 2.0, 3.0, 4.0, 5.0])

In [72]:
t1 @ t2

tensor(55.0)

In [90]:
t1.reshape(3,2) @ t2.reshape(2,3)

n1, n2 = len(t1.shape), len(t2.shape)
assert n1 != 0 and n2 != 0, f"both arguments to matmul need to be at least 1D, but they are {n1}D and {n2}D"
assert (L:=t1.shape[-1]) == (R:=t2.shape[-min(n2, 2)]), f"Input Tensor shapes {t1.shape} and {t2.shape} cannot be multiplied ({L} != {R})"
x = t1.reshape(*t1.shape[0:-1], *[1]*min(n1-1, n2-1, 1), t1.shape[-1])
t2 = t2.reshape(*t2.shape[0:-2], *[1]*min(n1-1, n2-1, 1), *t2.shape[-min(n2, 2):]).transpose(-1, -min(n2, 2))
t1.shape, t2.shape

((3, 1, 2), (1, 2, 3))

In [74]:
t1

tensor([[0, 1], [2, 3], [4, 5]])

In [75]:
t1[-1]

tensor([[4, 5]])

In [91]:
t1[-1,-1]

IndexError: index of -1 is out of bounds for dim with size 1

In [113]:
x0 = torch.arange(3*3*4)
x = x0.reshape(3,4,3)
w = torch.arange(5*3*3*4).reshape(5,3,3,4)

x[0,0,0] = 9000

x[0,0,0], x0[0]

(tensor(9000), tensor(9000))

In [108]:
x @ w

tensor([[[[   20,    23,    26,    29],
          [   56,    68,    80,    92],
          [   92,   113,   134,   155],
          [  128,   158,   188,   218]],

         [[  632,   671,   710,   749],
          [  776,   824,   872,   920],
          [  920,   977,  1034,  1091],
          [ 1064,  1130,  1196,  1262]],

         [[ 2108,  2183,  2258,  2333],
          [ 2360,  2444,  2528,  2612],
          [ 2612,  2705,  2798,  2891],
          [ 2864,  2966,  3068,  3170]]],


        [[[  128,   131,   134,   137],
          [  488,   500,   512,   524],
          [  848,   869,   890,   911],
          [ 1208,  1238,  1268,  1298]],

         [[ 2036,  2075,  2114,  2153],
          [ 2504,  2552,  2600,  2648],
          [ 2972,  3029,  3086,  3143],
          [ 3440,  3506,  3572,  3638]],

         [[ 4808,  4883,  4958,  5033],
          [ 5384,  5468,  5552,  5636],
          [ 5960,  6053,  6146,  6239],
          [ 6536,  6638,  6740,  6842]]],


        [[[  236,   239,