In [2]:
%load_ext autoreload
%autoreload 2
import numpy as np
from tinygrad import Tensor
import torch
import shrimpgrad as sg

In [ ]:
x = torch.arange(4, dtype=torch.float32).reshape(2,2)
y = torch.eye(2,dtype=torch.float32)
z = x.matmul(y)
x, y, z

In [6]:
x = sg.Tensor.arange(0, 4, dtype=sg.dtypes.float32).reshape(2,2)
y = sg.Tensor.eye(2, dtype=sg.dtypes.float32)
z = x.matmul(y)
x, y, z

(tensor([[0.0, 1.0], [2.0, 3.0]]),
 tensor([[1.0, 0.0], [0.0, 1.0]]),
 tensor([[0.0, 1.0], [2.0, 3.0]]))