In [2]:
%load_ext autoreload
%autoreload 2

import tensor as shrimp


In [127]:
t = arange(64,(4,4,4))

In [129]:
t, t[1:,1:,1:]

(tensor([[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]],
  [[16, 17, 18, 19], [20, 21, 22, 23], [24, 25, 26, 27], [28, 29, 30, 31]],
  [[32, 33, 34, 35], [36, 37, 38, 39], [40, 41, 42, 43], [44, 45, 46, 47]],
  [[48, 49, 50, 51], [52, 53, 54, 55], [56, 57, 58, 59], [60, 61, 62, 63]]]),
 tensor([[[21, 22, 23], [25, 26, 27], [29, 30, 31]],
  [[37, 38, 39], [41, 42, 43], [45, 46, 47]],
  [[53, 54, 55], [57, 58, 59], [61, 62, 63]]]))

In [130]:
t[0]

tensor([[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]])

In [131]:
t[-1]

tensor([[[48, 49, 50, 51], [52, 53, 54, 55], [56, 57, 58, 59], [60, 61, 62, 63]]])

In [134]:
t[3:] # Fix

tensor([[[48, 49, 50, 51], [52, 53, 54, 55], [56, 57, 58, 59], [60, 61, 62, 63]]])

In [154]:
t = torch.arange(64).reshape(4,4,4)[3:]

In [155]:
t.item()

RuntimeError: a Tensor with 16 elements cannot be converted to Scalar

In [138]:
t[4]

IndexOutOfBounds: Index out of bounds: 4 <= 4

In [140]:
t1 = torch.arange(10)
t2 = torch.arange(9)
t1.matmul(t2)

RuntimeError: inconsistent tensor size, expected tensor [10] and src [9] to have the same number of elements, but got 10 and 9 elements respectively

In [238]:
t1 = torch.arange(10)
print(t1)
t2 = torch.arange(10)
t3 = t1.matmul(t2)
t3.item()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


285

In [5]:
t1 = shrimp.arange(10).reshape(5,2)
t2 = shrimp.arange(10).reshape(2,5)
t1.data
t2.data
(ctypes.c_int * t1.size)(*a.data)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [202]:
t1 = torch.arange(10).reshape(1,10)
t1

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])