In [19]:
%load_ext autoreload
%autoreload 2


import tensor as shrimp
import torch

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [127]:
t = arange(64,(4,4,4))

In [129]:
t, t[1:,1:,1:]

(tensor([[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]],
  [[16, 17, 18, 19], [20, 21, 22, 23], [24, 25, 26, 27], [28, 29, 30, 31]],
  [[32, 33, 34, 35], [36, 37, 38, 39], [40, 41, 42, 43], [44, 45, 46, 47]],
  [[48, 49, 50, 51], [52, 53, 54, 55], [56, 57, 58, 59], [60, 61, 62, 63]]]),
 tensor([[[21, 22, 23], [25, 26, 27], [29, 30, 31]],
  [[37, 38, 39], [41, 42, 43], [45, 46, 47]],
  [[53, 54, 55], [57, 58, 59], [61, 62, 63]]]))

In [130]:
t[0]

tensor([[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]])

In [131]:
t[-1]

tensor([[[48, 49, 50, 51], [52, 53, 54, 55], [56, 57, 58, 59], [60, 61, 62, 63]]])

In [134]:
t[3:] # Fix

tensor([[[48, 49, 50, 51], [52, 53, 54, 55], [56, 57, 58, 59], [60, 61, 62, 63]]])

In [154]:
t = torch.arange(64).reshape(4,4,4)[3:]

In [155]:
t.item()

RuntimeError: a Tensor with 16 elements cannot be converted to Scalar

In [138]:
t[4]

IndexOutOfBounds: Index out of bounds: 4 <= 4

In [140]:
t1 = torch.arange(10)
t2 = torch.arange(9)
t1.matmul(t2)

RuntimeError: inconsistent tensor size, expected tensor [10] and src [9] to have the same number of elements, but got 10 and 9 elements respectively

In [238]:
t1 = torch.arange(10)
print(t1)
t2 = torch.arange(10)
t3 = t1.matmul(t2)
t3.item()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


285

In [52]:
import ctypes
t1 = shrimp.arange(1000).reshape(50,20)
t2 = shrimp.arange(1000).reshape(20,50)
t1.matmul(t2)

# c_arr = (ctypes.c_double * t1.size)(*t1.data)
# for i in c_arr:
#     print(i)

tensor([[123500.0,
  123690.0,
  123880.0,
  124070.0,
  124260.0,
  124450.0,
  124640.0,
  124830.0,
  125020.0,
  125210.0,
  125400.0,
  125590.0,
  125780.0,
  125970.0,
  126160.0,
  126350.0,
  126540.0,
  126730.0,
  126920.0,
  127110.0],
 [127300.0,
  127490.0,
  127680.0,
  127870.0,
  128060.0,
  128250.0,
  128440.0,
  128630.0,
  128820.0,
  129010.0,
  129200.0,
  129390.0,
  129580.0,
  129770.0,
  129960.0,
  130150.0,
  130340.0,
  130530.0,
  130720.0,
  130910.0],
 [131100.0,
  131290.0,
  131480.0,
  131670.0,
  131860.0,
  132050.0,
  132240.0,
  132430.0,
  132620.0,
  132810.0,
  313500.0,
  314090.0,
  314680.0,
  315270.0,
  315860.0,
  316450.0,
  317040.0,
  317630.0,
  318220.0,
  318810.0],
 [319400.0,
  319990.0,
  320580.0,
  321170.0,
  321760.0,
  322350.0,
  322940.0,
  323530.0,
  324120.0,
  324710.0,
  325300.0,
  325890.0,
  326480.0,
  327070.0,
  327660.0,
  328250.0,
  328840.0,
  329430.0,
  330020.0,
  330610.0],
 [331200.0,
  331790.0,
  332

In [32]:
t1 = torch.arange(10, dtype=torch.float32).reshape(5,2)
t2 = torch.arange(10, dtype=torch.float32).reshape(2,5)
t1.matmul(t2)

tensor([[  5.,   6.,   7.,   8.,   9.],
        [ 15.,  20.,  25.,  30.,  35.],
        [ 25.,  34.,  43.,  52.,  61.],
        [ 35.,  48.,  61.,  74.,  87.],
        [ 45.,  62.,  79.,  96., 113.]])